"""empty message

Revision ID: 377197895f5a
Revises: 
Create Date: 2018-04-01 10:16:27.162323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377197895f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_table('step')
    op.add_column('description', sa.Column('audio', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('description', 'audio')
    op.create_table('step',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=True),
    sa.Column('num', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    # ### end Alembic commands ###
